/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */


// @require @packageOverrides
Ext.require('Ext.direct.*', function() {  
	
	var me = this;
	me.splashscreen = Ext.getBody().mask('应用加载中...', 'splashscreen');
	me.splashscreen.addCls('splashscreen');

	Ext.DomHelper.insertFirst(Ext.query('.x-mask-msg')[0], {
		cls: 'x-splash-icon'
	})	
    Ext.direct.Manager.addProvider(Ext.app.REMOTING_API);  
});

Ext.application({
	
	requires: [
	           'BPSPortal.override.picker.Date',
	           'BPSPortal.override.picker.Menu',
	           'Ext.dom.Element'
	       ],
    models: [
             'Base',
             'Address',
             'Customer',
             'CustomerBatch',
             'ContactInfo',
             'ProjectInfo',
             'CustBPSInfo',
             'CustRegInfo',
             'Dictionary',
             'ProdLine',
             'CustProdLine',
             'DealerInfo',
             'MaterialInfo',
             'DealerInfos',
             'Customers',
             'Region',
             'City',
             'UserBPS',
             'ParentCustomer',
             'PriceSpecialDetail',
             'PriceSpecial',
             'PriceStrategy',
             'PriceStrategys',
             'PriceStrategyss',
             'PriceStrategyAudit',
             'PriceStrategyDetail',
             'Trial',
             'Person',
             'PriceQuery',
             'PriceCode',
             'AddDealer',
             'BPSInfo',
             'UploadTaskInfo',
             'UploadReSale',
             'UploadInventory',
             'UploadInventoryAdjustment',
             'DealarV',
             'MaterialInfos',
             'ProdLines',
             'Dictionarys',
             'Regions',
             'DealerCurrency',
             'DealerProdLine',
             'BPSRole',
             'BPSMonthly',
             'DealerRegNum',
             'MaterialActiveInfo'
    ],
    stores: [
             
    ],
    views: [
        'main.MainView',
        'menu.MenuPanel',
        'customer.customerquery.CustomerQuery',
        'customer.customeradd.CustomerAdd',
        'customer.customerBatc.CustomerBatchProc',
        'customer.customeradd.CustomerView',
        'customer.reportapprove.ReportApprove',
        'customer.customerupdate.CustomerUpdate',
        'price.pricequery.PriceQuery',
        'price.policyquery.PolicyQuery',
        'price.pricepolicy.PricePolicy',
        'price.pricetrial.PriceTrial',
        'price.applicationquery.ApplicationQuery',
        'price.applicationapproval.ApplicationApproval',
        'price.priceapplication.PriceApplication',
        'returngoods.goodsquery.GoodsQuery',
        'returngoods.returninput.ReturnInput',
        'returngoods.priceinput.PriceInput',
        'returngoods.executiveinput.ExecutiveInput',
        'returngoods.monthoperation.MonthOperation',
        'returngoods.specialpriceinput.SpecialPriceInput',
        'customer.reportapprove.ReportDetail',
        'customer.reportapprove.ConflictQuery',
        'customer.reportapprove.UpdateStatus',
        'customer.customerupdate.UpdateStatusWin',
        'customer.customerupdate.UpdateWin',
        'customer.customeradd.CustomerReg',
        'user.PassWordWin',
        'help.MaterialPicker',
        'help.CustomerPicker',
        'help.ProjectPicker',
        'help.CityPicker',
        'help.MaterialPickers',
        'help.MaterialPickerss',
        'help.CustomerPickers',
        'help.PersonPicker',
        'help.DealerPicker',
        'help.PersonSalesPicker',
        'price.applicationapproval.ApprovalDetail',
        'price.applicationapproval.ApprovalUpdate',
        'customer.customeradd.CustomerUpdates',
        'price.applicationquery.ApprovalDetailView',
        'user.DealerAdd',
        'user.BPSAdd',
        'user.UpdateWin',
        'returngoods.salesconfirm.SalesConfirm',
        'returngoods.Inventory.Inventory',
        'returngoods.InventoryAdjustment.InventoryAdjustment',
        'returngoods.salesconfirm.SalesDetail',
        'returngoods.InventoryAdjustment.InventoryAdjustmentDetail',
        'returngoods.Inventory.InventoryDetail',
        'systemadministration.city.UpdateCity',
        'systemadministration.directory.Directory',
        'systemadministration.prodname.Prodname',
        'user.UpdateDealerWin',
        'returngoods.salesupload.SalesQuery',
        'returngoods.salesupload.SalesTaskQuery',
        'returngoods.salesupload.SalesUpload',
        'price.pricetrial.PriceTrialDetail',
        'systemadministration.person.Person',
        'systemadministration.prodperson.ProdPerson',
        'customer.customeradd.CustomerUpdates'
    ],	
    name: 'BPSPortal',
    appFolder : "ext5_app/app",
    
    launch : function() {
    	
		Ext.create('BPSPortal.view.main.MainView');
		var splashscreen = Ext.query('div.splashscreen',false);
		var names =new Array();
		Ext.each(splashscreen,function(item){
			item.fadeOut({
				duration : 10,
				remove : true
				
			});
		});
		
	}
});
