/*
 * File: app/view/BPSPortal/view/returngoods/priceinput/PriceInput.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BPSPortal.view.returngoods.specialpriceinput.SpecialPriceInput', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.specialpriceinput',

    requires: [
        'BPSPortal.view.returngoods.specialpriceinput.SpecialPriceInputViewModel',
        'BPSPortal.view.returngoods.specialpriceinput.SpecialPriceInputViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel'
    ],

    viewModel: {
        type: 'specialpriceinput'
    },
    title: '特价返货录入',
    closable: true,
    scrollable: true,
    items: [
        {
            xtype: 'form',
            height: 141,
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'container',
                    padding: '10 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '调价周期'
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 50',
                            fieldLabel: '经销商'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '10 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            flex: 1,
                            fieldLabel: '',
                            boxLabel: '是否重算'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: '计算'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            title: '',
            height:200,
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '调价期间'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '经销商'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '金额'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '文件编号'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '执行状态'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '备注'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '确认'
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        },
        {
            xtype: 'gridpanel',
            title: '特价返货数据',
            height:200,
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '经销商'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '客户编码'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '客户名称'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '订单编号'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '订单金额'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '订单时间'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '订单状态'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '订单金额（含税）'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '订单总金额（含税）'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '特价金额（单价含税）'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '特价差异（总金额含税）'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '返货总金额'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '确认'
                        }
                    ]
                }
            ]
        }
    ]

});