/*
 * File: app/view/BPSPortal/view/returngoods/priceinput/PriceInput.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BPSPortal.view.returngoods.priceinput.PriceInput', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.priceinput',

    requires: [
        'BPSPortal.view.returngoods.priceinput.PriceInputViewModel',
        'BPSPortal.view.returngoods.priceinput.PriceInputViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel'
    ],

    viewModel: {
        type: 'priceinput'
    },
    title: '调价返货录入',
    closable: true,
    scrollable: true,
    items: [
        {
            xtype: 'form',
            height: 170,
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'container',
                    padding: '10 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '调价期间'
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 50',
                            fieldLabel: '经销商'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '10 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '价格政策'
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 50',
                            fieldLabel: '上期价格政策'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '10 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            flex: 1,
                            fieldLabel: '',
                            boxLabel: '是否重算'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    border:false,
                    items: [
                        {
                            xtype: 'button',
                            text: '计算'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            title: '',
            height:200,
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '调价期间'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'number',
                    text: '经销商'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'date',
                    text: '金额'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'bool',
                    text: '文件编号'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'bool',
                    text: '执行状态'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'bool',
                    text: '备注'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '确认'
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        },
        {
            xtype: 'gridpanel',
            title: '试算明细',
            height:200,
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '经销商'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '产品编码'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '产品名称'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '库存量'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '价格政策A'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '价格政策B'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '价差'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '导出'
                        }
                    ]
                }
            ]
        }
    ]

});